options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/iron-dynamics-440303-r9/fastapi-app:lastest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/iron-dynamics-440303-r9/fastapi-app:lastest']

images:
  - 'gcr.io/iron-dynamics-440303-r9/fastapi-app:lastest'