options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/iron-dynamics-440303-r9/fastapi-app:lastest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/iron-dynamics-440303-r9/fastapi-app:lastest']
# Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'fast-api-test', '--image', 'gcr.io/iron-dynamics-440303-r9/fastapi-app:lastest', '--region', 'us-central1', '--platfrom', 'managed']

images:
  - 'gcr.io/iron-dynamics-440303-r9/fastapi-app:lastest'

